- name: Install tools
  hosts: all
  tasks:
    - apt: name={{ item }} state=present
      with_items:
        - vim
        - htop
        - tree
        - sysstat
        - tcpdump
        - rsync

- name: debug various
  hosts: all
  tasks:
    - debug:
        msg: "for various debug purposes, like variables printing {{ data_dir }}"

- name: Install Docker-ce for x86 arch
  hosts: all
  tasks:
  - name: Install prerequisites
    apt: name={{item}} update_cache=yes
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common

  - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

  - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

  - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
      pip:
        name: docker
