- name: Install tools
  hosts: all
  tasks:
    - apt: name={{ item }} state=present
      with_items:
        - python-pip
        - virtualenv
        - python3-setuptools
        - vim
        - htop
        - tree
        - sysstat
        - tcpdump
        - rsync

- name: debug various
  hosts: all
  tasks:
    - debug:
        msg: "for various debug purposes, like variables printing {{ data_dir }}"

- name: Install Docker-ce for x86 arch
  hosts: all
  tasks:
  - name: Install prerequisites
    apt: name={{item}} update_cache=no
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: install docker
    package:
      name: docker-ce
      state: present

  - name: Install Docker Module for Python
    pip:
      name: docker