- name: Install tools
  hosts: all
  tasks:
    - apt: name={{ item }} state=present
      with_items:
        - vim
        - htop
        - tree
        - sysstat
        - tcpdump
        - rsync

  - name: debug various
    hosts: all
    tasks:
      - debug:
          msg: "for various debug purposes, like variables printing {{ data_dir }}"

- name: Install Docker-ce for x86 arch
  hosts: all
  tasks:
  - name: Install prerequisites
    apt: name={{item}} update_cache=yes
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/debian/gpg
  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
  - name: install docker
    package:
      name: docker-ce
      state: present

- name: Install docker-py module for python3
  hosts: all
  tasks:
    - pip:
        name: docker-py
